### ISSUE TITLE
AccessControl and Submit button for Registration

### ISSUE THREAD

**Issue by omarmmousa** [Ronald-C/Clubin-#15]
@Ronald-C We will need this fixed ASAP can't test if our sign-up page is sending to the database needs to incorporated into Signup.html 

trying to run tests to store students into the database but getting errors!!

**Comment by Ronald-C** [comment]
@ceilingphan Is /sRegistration working?

**Comment by ghost** [comment]
Works fine for me. I added a student five minutes ago.

**Comment by ghost** [comment]
If this is about the submit button being disabled after an error, that has been fixed earlier today.
