### ISSUE TITLE
Research flask stormpath warning

### ISSUE THREAD

**Issue by Ronald-C** [Ronald-C/Clubin-#5]
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by Yomz** [comment]
The only workarounds to both warnings is to upgrade to newer version of Python. (versions of Python earlier than 2.7.9 have trouble with SNI and restrictions on their ssl module)

An alternative to upgrading python version is to simply disable the warnings, which is not recommended. To do so:
import urllib3
urllib3.disable_warnings()
----------- OR ---------------
logging.captureWarnings(True)

**Comment by Ronald-C** [comment]
Thanks! Closing issue ticket.
- Advised not to upgrade system python due to dependencies. 
- Optional to install under virtualenv.
